services:

  #backend
  backend:
    build:
      context: ./backend
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, backend:80
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}

      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}

      DATABASE_URL: mysql://app:masha@database:3306/kalinka_db?serverVersion=8.0.32&charset=utf8mb4
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://backend/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}

    volumes:
      - ./backend:/app
      - caddy_data:/data
      - caddy_config:/config

    ports:
      - "8000:80"
      - "443:443"

    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:${MYSQL_VERSION:-8.0.32}
    environment:
      MYSQL_ROOT_PASSWORD: masha
      MYSQL_DATABASE: kalinka_db
      MYSQL_USER: app
      MYSQL_PASSWORD: masha
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s


  #frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
  database_data:
  backend_vendor: