---
# Production environment override
services:
  backend:
    image: ${IMAGES_PREFIX:-}app-php-prod
    build:
      context: ./backend
      target: frankenphp_base
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
